### ISSUE TITLE
Bad command or filename - "c:\_run.bat"

### ISSUE THREAD

**Issue by roc-italy** [henrikstengaard/HstDOS#1]
Hi Henrik,

I have been trying to setup the HstDOS with my games collection. 

Maybe I am doing something wonky, but I managed to create the hstdos.ini file for each game/folder. I have listed also either the executable to be launched or a batch file to choose among the different audio options. 

Please find below an example of the hstdos.ini for the Doom_1 directory:

[menu]
title=Doom_1
autostart=Doom.exe

I can see and browse all the entries in the HstDOS, however when selecting a game the c:\_run.bat doesn't seem to be created, because it returns an error:

Bad command or filename - "c:\_run.bat"

I tested HstDOS  from both C and from E,.Needless to say, I have included the hstdos directory in the autoexec.bat path.

I am using DosBox-X and tried it from both DOS 6.22 and FreeDOS 1.3.

Thank you for any advise.

**Comment by henrikstengaard** [comment]
HstDOS uses `TEMP` environment variable to determine where to write it's run file to start selected menu entry. My examples unfortunately didn't include must details about this and I'm sure it can be solved by adding the line `SET TEMP=C:\` in your autoexec.bat. You also want to change a line in the file `hd.bat` and replace line `call c:\_run.bat` with `call %TEMP%_run.bat` so HstDOS calls the run file properly.

**Comment by roc-italy** [comment]
Many thanks! 

"call  %TEMP%\_run.bat" works just fine ;-)

Edit:
For some reason, this editor cuts the backslash after the %Temp%: For those using it, it is %temp% backslash _run.bat
